package com.example.sudokugame.controller;

import com.example.sudokugame.view.GameStage;
import com.example.sudokugame.view.HomeStage;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;

import java.io.IOException;

/**
 * Controller for the home screen of the Sudoku game
 * Manages user interactions with the home screen.
 * @author Isabela bermúdez and Julieta Arteta
 * @version 1.0
 */


public class HomeController {

    /**
     * Initialization method automatically called by JavaFX after FXML elements are loaded.
     */

    @FXML
    public void initialize() {
        System.out.println("hola");
    }
    @FXML
    private Button buttonPLay;

    /**
     * handles the event on the "Play" button.
     * Creates a new instance of the game window and closes the home screen.
     * @param event The action event generated by the button
     * @throws IOException if an error occurs while loading FXML file
     */

    @FXML
    void handlePlay(ActionEvent event) throws IOException {
        System.out.println("Play");

        GameStage gameStage = new GameStage();
        HomeStage.deleteInstance();

    }
}
